# Generated by Django 5.2.11 on 2026-02-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('uploaded_image', models.ImageField(upload_to='')),
                ('extracted_text', models.TextField(blank=True)),
                ('marks', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
