# Generated by Django 5.2.11 on 2026-02-07 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='marks',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='uploaded_image',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_answers/'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='matched_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='missing_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(choices=[('Q1', 'Question 1'), ('Q2', 'Question 2'), ('Q3', 'Question 3'), ('Q4', 'Question 4'), ('Q5', 'Question 5')], max_length=10)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('model_answer', models.TextField(help_text="Teacher's model answer")),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='autograder.question'),
        ),
    ]
