# Generated by Django 5.2.11 on 2026-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0002_rename_marks_studentanswer_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='keywords',
            field=models.TextField(help_text='Comma-separated keywords for grading'),
        ),
        migrations.AlterField(
            model_name='question',
            name='model_answer',
            field=models.TextField(help_text="Teacher's ideal answer"),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Original question image', null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Extracted from image via OCR'),
        ),
    ]
